
services:
  db:
    image: postgres:13
    hostname: db
    environment:
      POSTGRES_DB: myshop_db
      POSTGRES_USER: myshop_user
      POSTGRES_PASSWORD: myshop_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myshop_net

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./myshop:/myshop
      - ./static:/vol/web/static  
      - ./media:/vol/web/media
    environment:
      - DEBUG=1
      - DB_NAME=myshop_db
      - DB_USER=myshop_user
      - DB_PASSWORD=myshop_password
      - DB_HOST=db
      - DB_PORT=5432
      - DATABASE_URL=postgres://myshop_user:myshop_password@db:5432/myshop_db
      - CELERY_BROKER=REDIS://REDIS:6379/0/
      - DEBUG=1
    depends_on:
      - db
    command: sh -c "python manage.py runserver 0.0.0.0:8080"
    networks:
      - myshop_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - myshop_net


networks:
  myshop_net:

volumes:
  postgres_data: