version: '3.8'
services:
  db:
    image: postgres:13
    hostname: db
    environment:
      POSTGRES_DB: myshop_db
      POSTGRES_USER: myshop_user
      POSTGRES_PASSWORD: myshop_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - myshop_net

  app:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./static:/vol/web/static  
      - ./media:/vol/web/media
    environment:
      - DEBUG=1
    depends_on:
      - db
    command: /scripts/entrypoint.sh
    networks:
      - myshop_net

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - myshop_net

networks:
  myshop_net:

volumes:
  postgres_data: