# Generated by Django 4.2 on 2024-07-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='image',
            new_name='image_one',
        ),
        migrations.AddField(
            model_name='category',
            name='image_two',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
    ]
