# Generated by Django 4.2 on 2025-01-27 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_has_size_alter_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_size',
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=1),
        ),
    ]
